action_space : ['take', 'move', 'die']
character : ['@', '$', '&', '+']
edge_conditions : ['none','touch', 'step']
step_range : [1,10]
seed : 'any'
sim_speed : 0.2  # in seconds, speed of simulation
save_log : true
log_file : 'log_[<SEED>].txt' # <SEED> will be replaced by the seed value
min_log : 10                  # minimum number of steps to log