width : 30
height : 15
action_space : ['idle','take', 'move', 'die', 'chase', 'clone','add','transform','push','move_wall']
character : ['@', '$', '&', '+', ';', '!', '>', '<', 'X', 'O', '*', '^']
edge_conditions : ['none','touch', 'step', 'within', 'nextTo']
step_range : [1,10]
prox_range : [1,10]
seed : 463858              # 'any' or a number
sim_speed : 0.45                # in seconds, speed of simulation
save_log : true
log_file : 'LOGS/log_[<SEED>].txt' # <SEED> will be replaced by the seed value
min_log : 10                  # minimum number of steps to log
inactive_limit : 20           # how long to let the simulation run before stopping due to inactivity
pop_perc : 0.25              # maximum percentage of the map for entities to spawn on
min_view : true             # render in minimalist view